# Generated by Django 4.1.3 on 2022-11-19 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='discont',
            new_name='discount',
        ),
    ]
