# Generated by Django 4.1.3 on 2022-11-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_discont_offer_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='cupon_code',
            new_name='coupon_code',
        ),
    ]
